spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    client-id: ${KAKAO_REST_API_KEY}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2

  kakao:
    pay:
      admin-key: ${KAKAO_PAY_ADMIN_KEY}
      secret-key: ${KAKAO_PAY_SECRET_KEY}
      cid: ${KAKAO_PAY_CID}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
