name: PROTOTYNE BE auto deploy workflows

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    name: BE 코드 빌드 및 배포
    runs-on: ubuntu-latest

    steps:
      - name: BE repo 체크아웃
        uses: actions/checkout@v3
        
      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew
        
      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 빌드
        run: ./gradlew clean build -x test

      - name: DockerHub 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        run: |
          IMAGE_TAG=1.0.${{ github.run_number }}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/live_server:${IMAGE_TAG} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/live_server:${IMAGE_TAG} ${{ secrets.DOCKERHUB_USERNAME }}/live_server:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/live_server:${IMAGE_TAG}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/live_server:latest
      
      - name: manifest repo 이미지 경로 수정
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://x-access-token:${{ secrets.MANIFEST_REPO_PAT }}@github.com/PROTOTYNE/PROTOTYNE_manifest.git
          cd PROTOTYNE_manifest/k8s
          sed -i 's|^\(\s*image:\s*\).*|\1'"${{ secrets.DOCKERHUB_USERNAME }}"'/live_server:'"${IMAGE_TAG}"'|' deployment.yaml
          git add deployment.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci(manifest): update image to ${IMAGE_TAG} via GitHub Actions [skip ci]"
            git push
          fi

